#!/bin/bash

set -e

if [ $EUID = 0 ]; then
    echo please don't run me as root, i'll sudo for my damned self
    exit 1
fi

sudo apt-get install \
    libcurl4-openssl-dev \
    python-dev \
    python-pip \
    python-virtualenv \
    ;

mkdir -p ~/venv
cd ~/venv
virtualenv harold

(
    source ~/venv/harold/bin/activate
    pip install --upgrade pip setuptools
    pip install -r ~/src/harold/requirements.txt
    python ~/src/harold/setup.py develop
)

cat <<SALON | sudo tee /etc/init/harold-salon.conf
description "the salon dashboard"

start on runlevel [2345]
stop on runlevel [016]

respawn

script
    . ${HOME}/venv/harold/bin/activate

    export HAROLD_CONFIG=${HOME}/src/harold/example.ini
    export SALON_CONFIG=${HOME}/src/harold/example-salon.conf

    exec gunicorn \\
        --bind=0.0.0.0:80 \\
        --workers=1 \\
        --user=${USER} --group=${USER} \\
        salon.app:app
end script
SALON

cat <<BOT | sudo tee /etc/init/harold-bot.conf
description "the harold slackbot / webhook receiver"

start on runlevel [2345]
stop on runlevel [016]

respawn

script
    . ${HOME}/venv/harold/bin/activate

    export HAROLD_CONFIGURATION=${HOME}/src/harold/example.ini

    exec twistd \\
        --uid=${USER} --gid=${USER} \\
        --nodaemon --pidfile="" --no_save \\
        --python ${HOME}/src/harold/harold.tac
end script
BOT

start harold-salon
start harold-bot
